# Site settings
title: CMPT 479/980
subtitle: Systems and Network Security – Spring 2020
description: |
             XXXX
             XXXX
baseurl: "/sp20" # the subpath of your site, e.g. /blog/
url: "https://netsys-security.github.io" # the base hostname & protocol for your site
syllabus: "xxx"
githubdir: "netsys-security/sp20"

# Author/user information
email: kdiab@sfu.ca
twitter_username: khaledmdiab
github_username:  khaledmdiab
authorurl: "http://sfu.ca/~kdiab"


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
